invalid_image: "Image must be within the following dimensions 300*300 to 5000*5000"
image_exists: "The specified image already exists."
image_not_present: "The specified image doesn't exists"
directory_exists: "The specified directory already exists."
directory_not_present: "Couldn't find the root folder. The root folder has to be present in order perform actions on it"
something_wrong: "Something went wrong when making the request"
unknown_extension: "Unknown extension, allowed are png, jpeg and gif"
invalid_create_image_request: "It should contain a directory_id, file_name, content_type and the actual image"